name: Build package

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install stockfish
      - name: Lint with black
        run: |
          pip install black
          black --check .
      - name: Check type annotations with mypy
        run: |
          pip install mypy
          mypy stockfish tests
      - name: Test with pytest
        run: |
          pip install pytest
          export PATH=$PATH:/usr/games/
          pytest
